In [1]:
import pandas as pd

# Companys

In [58]:
comp = pd.read_csv("data/companys.csv")
comp

   Company ID Company name           Region
0           1        Огонь        Сибирский
1           2         Вода      Центральный
2           3        Земля  Северо-Западный
3           4       Воздух      Приволжский
4           5       Металл        Уральский

In [27]:
comp.loc[0, 'Регион'] = 'Сибирский'

comp

   Id Company name           Region     Регион
0   1        Огонь        Сибирский  Сибирский
1   2         Вода      Центральный        NaN
2   3        Земля  Северо-Западный        NaN
3   4       Воздух      Приволжский        NaN
4   5       Металл        Уральский        NaN

In [29]:
comp.rename(columns={
    'Id': 'Company ID',
    'Название кампании': 'Company name',
    'Регион': 'Region'
}, inplace=True)

In [30]:
comp

   Company ID Company name           Region
0           1        Огонь        Сибирский
1           2         Вода      Центральный
2           3        Земля  Северо-Западный
3           4       Воздух      Приволжский
4           5       Металл        Уральский

In [59]:
comp['Company ID'] = comp['Company ID'].astype(int)

In [60]:
comp.to_csv("data/companys.csv", index=False)

# Customers

In [19]:
cust = pd.read_csv('data/customers.csv', encoding="cp1251", sep= ';')

cust

    ID клиента                 Email      Телефон           Регион
0            1    email1@example.com  79991234501        Сибирский
1            2    email2@example.com  79991234502      Центральный
2            3    email3@example.com  79991234503  Северо-Западный
3            4    email4@example.com  79991234504      Приволжский
4            5    email5@example.com  79991234505      Приволжский
..         ...                   ...          ...              ...
95          96   email96@example.com  79991234596      Центральный
96          97   email97@example.com  79991234597      Приволжский
97          98   email98@example.com  79991234598        Сибирский
98          99   email99@example.com  79991234599  Северо-Западный
99         100  email100@example.com  7,99912E+11        Уральский

[100 rows x 4 columns]

In [23]:
cust['Телефон'] = cust['Телефон'].astype(str)
cust.loc[cust['Телефон'] == '7,99912E+11', 'Телефон'] = '79991234599'

cust

    ID клиента                 Email      Телефон           Регион
0            1    email1@example.com  79991234501        Сибирский
1            2    email2@example.com  79991234502      Центральный
2            3    email3@example.com  79991234503  Северо-Западный
3            4    email4@example.com  79991234504      Приволжский
4            5    email5@example.com  79991234505      Приволжский
..         ...                   ...          ...              ...
95          96   email96@example.com  79991234596      Центральный
96          97   email97@example.com  79991234597      Приволжский
97          98   email98@example.com  79991234598        Сибирский
98          99   email99@example.com  79991234599  Северо-Западный
99         100  email100@example.com  79991234599        Уральский

[100 rows x 4 columns]

In [61]:
cust = pd.read_csv('data/customers.csv')
cust

    ID клиента                 Email      Телефон           Регион
0            1    email1@example.com  79991234501        Сибирский
1            2    email2@example.com  79991234502      Центральный
2            3    email3@example.com  79991234503  Северо-Западный
3            4    email4@example.com  79991234504      Приволжский
4            5    email5@example.com  79991234505      Приволжский
..         ...                   ...          ...              ...
95          96   email96@example.com  79991234596      Центральный
96          97   email97@example.com  79991234597      Приволжский
97          98   email98@example.com  79991234598        Сибирский
98          99   email99@example.com  79991234599  Северо-Западный
99         100  email100@example.com  79991234599        Уральский

[100 rows x 4 columns]

In [62]:
cust['ID клиента'] = cust['ID клиента'].astype(int)

In [63]:
cust.to_csv("data/customers.csv", index=False)

# Products

In [44]:
prod = pd.read_csv('data/productss.csv', encoding="cp1251", sep= ';')

prod

     ID товара Название товара    Категория Стоимость
0            1         Товар 1  Электроника      2475
1            2         Товар 2  Электроника      -186
2            3         Товар 3       Одежда      5483
3            4         Товар 4      Красота      9177
4            5         Товар 5          Дом      6485
..         ...             ...          ...       ...
97          96        Товар 96       Одежда      8937
98          97        Товар 97       Одежда      7265
99          98        Товар 98  Электроника      1910
100         99        Товар 99      Красота      6686
101        100       Товар 100  Электроника      7888

[102 rows x 4 columns]

In [45]:
prod.loc[prod['Название товара']== 'Товар 9']

    ID товара Название товара Категория Стоимость
8           9         Товар 9    Одежда      5261
9           9         Товар 9    Одежда      5261
10          9         Товар 9    Одежда       NaN

In [46]:
prod.drop(index=[9, 10], inplace=True)

In [47]:
prod['Стоимость'].dtype

dtype('O')

In [48]:
prod = prod[prod['Название товара'] != 'Товар 90']

In [ ]:
prod['Стоимость'] = prod['Стоимость'].astype(int)

C:\Users\user\AppData\Local\Temp\ipykernel_13160\2160212685.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod['Стоимость'] = prod['Стоимость'].astype(int)

In [52]:
prod['Стоимость'].dtype

dtype('int32')

In [53]:
prod = prod[prod['Стоимость'] != -186]

In [54]:
prod.rename(columns={
    'ID товара': 'Product ID',
    'Название товара': 'Product name',
    'Категория': 'Category',
    'Стоимость': 'Price'
}, inplace=True)

prod

     Product ID Product name     Category  Price
0             1      Товар 1  Электроника   2475
2             3      Товар 3       Одежда   5483
3             4      Товар 4      Красота   9177
4             5      Товар 5          Дом   6485
5             6      Товар 6  Электроника   1999
..          ...          ...          ...    ...
97           96     Товар 96       Одежда   8937
98           97     Товар 97       Одежда   7265
99           98     Товар 98  Электроника   1910
100          99     Товар 99      Красота   6686
101         100    Товар 100  Электроника   7888

[98 rows x 4 columns]

In [64]:
prod = pd.read_csv('data/productss.csv')
prod

    Product ID Product name     Category  Price
0            1      Товар 1  Электроника   2475
1            3      Товар 3       Одежда   5483
2            4      Товар 4      Красота   9177
3            5      Товар 5          Дом   6485
4            6      Товар 6  Электроника   1999
..         ...          ...          ...    ...
93          96     Товар 96       Одежда   8937
94          97     Товар 97       Одежда   7265
95          98     Товар 98  Электроника   1910
96          99     Товар 99      Красота   6686
97         100    Товар 100  Электроника   7888

[98 rows x 4 columns]

In [65]:
prod['Product ID'] = prod['Product ID'].astype(int)

In [66]:
prod.to_csv('data/productss.csv', index=False)

# Sales

In [72]:
sales = pd.read_csv('data/sales.csv', encoding='cp1251', sep=';')
sales

    Дата продажи  ID товара  ID клиента  Количество  Скидка, %  ID компании
0     1672597726        4.0        22.0         9.0        0.0          3.0
1     1672684126       30.0        86.0         7.0        0.0          2.0
2     1672770526       93.0        83.0        10.0       10.0          1.0
3     04.01.2023       40.0        80.0         3.0       10.0          2.0
4     05.01.2023       98.0        85.0         8.0       10.0          2.0
..           ...        ...         ...         ...        ...          ...
360   26.12.2023       71.0        74.0         8.0        0.0          2.0
361   27.12.2023       29.0        90.0       -10.0       15.0          3.0
362   28.12.2023       16.0        99.0         5.0       10.0          4.0
363   29.12.2023       84.0         7.0         8.0       20.0          2.0
364   30.12.2023       93.0        57.0         7.0        0.0          5.0

[365 rows x 6 columns]

In [73]:
sales.drop(index=[0, 1, 2], inplace=True)
sales

    Дата продажи  ID товара  ID клиента  Количество  Скидка, %  ID компании
3     04.01.2023       40.0        80.0         3.0       10.0          2.0
4     05.01.2023       98.0        85.0         8.0       10.0          2.0
5     06.01.2023       91.0        41.0         4.0       10.0          5.0
6     07.01.2023       21.0        42.0         9.0       15.0          5.0
7     08.01.2023       57.0        53.0         6.0       10.0          4.0
..           ...        ...         ...         ...        ...          ...
360   26.12.2023       71.0        74.0         8.0        0.0          2.0
361   27.12.2023       29.0        90.0       -10.0       15.0          3.0
362   28.12.2023       16.0        99.0         5.0       10.0          4.0
363   29.12.2023       84.0         7.0         8.0       20.0          2.0
364   30.12.2023       93.0        57.0         7.0        0.0          5.0

[362 rows x 6 columns]

In [74]:
sales = sales[sales['Количество'] >= 0]
sales

    Дата продажи  ID товара  ID клиента  Количество  Скидка, %  ID компании
3     04.01.2023       40.0        80.0         3.0       10.0          2.0
4     05.01.2023       98.0        85.0         8.0       10.0          2.0
5     06.01.2023       91.0        41.0         4.0       10.0          5.0
6     07.01.2023       21.0        42.0         9.0       15.0          5.0
7     08.01.2023       57.0        53.0         6.0       10.0          4.0
..           ...        ...         ...         ...        ...          ...
359   25.12.2023       82.0        25.0         2.0       20.0          2.0
360   26.12.2023       71.0        74.0         8.0        0.0          2.0
362   28.12.2023       16.0        99.0         5.0       10.0          4.0
363   29.12.2023       84.0         7.0         8.0       20.0          2.0
364   30.12.2023       93.0        57.0         7.0        0.0          5.0

[360 rows x 6 columns]

In [76]:
sales = sales[sales['ID товара'] <= 100]
sales

    Дата продажи  ID товара  ID клиента  Количество  Скидка, %  ID компании
3     04.01.2023       40.0        80.0         3.0       10.0          2.0
4     05.01.2023       98.0        85.0         8.0       10.0          2.0
5     06.01.2023       91.0        41.0         4.0       10.0          5.0
6     07.01.2023       21.0        42.0         9.0       15.0          5.0
7     08.01.2023       57.0        53.0         6.0       10.0          4.0
..           ...        ...         ...         ...        ...          ...
359   25.12.2023       82.0        25.0         2.0       20.0          2.0
360   26.12.2023       71.0        74.0         8.0        0.0          2.0
362   28.12.2023       16.0        99.0         5.0       10.0          4.0
363   29.12.2023       84.0         7.0         8.0       20.0          2.0
364   30.12.2023       93.0        57.0         7.0        0.0          5.0

[359 rows x 6 columns]

In [77]:
sales['ID клиента'] = sales['ID клиента'].astype(int)
sales['ID товара'] = sales['ID товара'].astype(int)
sales['ID компании'] = sales['ID компании'].astype(int)

sales.rename(columns={
    'Дата продажи': 'Date',
    'ID товара': 'Product ID',
    'ID клиента': 'Client ID',
    'Количество': 'Count',
    'Скидка, %': 'Discount, %',
    'ID компании': 'Company ID'
}, inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_13160\442494571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['ID клиента'] = sales['ID клиента'].astype(int)
C:\Users\user\AppData\Local\Temp\ipykernel_13160\442494571.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['ID товара'] = sales['ID товара'].astype(int)
C:\Users\user\AppData\Local\Temp\ipykernel_13160\442494571.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['ID компании'] = sales['ID компании'].astype(int)
C:\Users\user\AppData\Local\Temp\ipykernel_13160\442494571.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales.rename(columns={

In [78]:
sales.to_csv('data/sales.csv', index=False)